import {createAsyncThunk, createSlice} from '@reduxjs/toolkit';
import {RootState} from '../../app/store';
import {User} from "../../models/User";
import {getUsersList} from "./usersAPI";

export interface UsersFilters {
    isActive?: boolean | null;
    isStaff?: boolean | null;
    isSuperuser?: boolean | null;
}

export interface UsersState {
    loading: boolean;
    error?: any | null;
    users: User[];
    totalUsers: number;
    currentPage: number;
    filters?: UsersFilters;
    search?: string | null;
    sorting?: string | null;
    nextPage?: string | null;
    previousPage?: string | null;
}

const initialState: UsersState = {
    loading: true,
    error: null,
    users: [],
    totalUsers: 0,
    currentPage: 1
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getUsersListAsync = createAsyncThunk(
    'users/getUsersList',
    async (_, thunkAPI) => {
        try {
            const {data} = await getUsersList();

            return data;
        } catch (err) {
            return thunkAPI.rejectWithValue(err);
        }
    }
);

export const usersSlice = createSlice({
    name: 'users',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getUsersListAsync.pending, (state) => {
                state.loading = true;
                state.error = null;
                state.users = [];
            })
            .addCase(getUsersListAsync.fulfilled, (state, action) => {
                state.loading = false;
                state.users = action.payload.results;
                state.totalUsers = action.payload.count;
                state.nextPage = action.payload.next;
                state.previousPage = action.payload.previous;
            })
            .addCase(getUsersListAsync.rejected, (state, action) => {
                state.loading = false;
                state.users = [];
                state.error = action.payload;
            })
    },
});

// export const {} = usersSlice.actions; // Uncomment this if we create any other actions.

export const selectUsers = (state: RootState) => state.users;

export default usersSlice.reducer;
